package com.example.demo2;

import java.time.LocalDateTime;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/task") // This means URL's start with /task (after Application path)
public class TaskController {

    @Autowired // This means to get the bean called taskRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private TaskRepository taskRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody String addNewTask(@RequestParam Users user,
            @RequestParam String task_name,
            @RequestParam String description,
            @RequestParam LocalDateTime due_date,
            @RequestParam Boolean is_completed) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Tasks t = new Tasks();
        t.setUser(user);
        t.setTaskName(task_name);
        t.setDescription(description);
        t.setDueDate(due_date);
        t.setIsCompleted(is_completed);
        taskRepository.save(t);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<Tasks> getAllTasks() {
        // This returns a JSON or XML with the tasks
        return taskRepository.findAll();
    }

        @DeleteMapping(path = "/delete") // Map ONLY DELETE Requests
    public @ResponseBody String deleteTask(@RequestParam Integer task_id) {
        // Check if task exists
        if (taskRepository.existsById(task_id)) {
            taskRepository.deleteById(task_id);
            return "Deleted";
        } else {
            return "Task not found";
        }
    }

    @PutMapping(path = "/update") // Map ONLY PUT Requests
    public @ResponseBody String updateTask(@RequestParam Integer task_id,
                                           @RequestParam String task_name,
                                           @RequestParam String description,
                                           @RequestParam LocalDateTime due_date,
                                           @RequestParam Boolean is_completed) {
        // Check if task exists
        if (taskRepository.existsById(task_id)) {
            Tasks t = taskRepository.findById(task_id).get();
            t.setTaskName(task_name);
            t.setDescription(description);
            t.setDueDate(due_date);
            t.setIsCompleted(is_completed);
            taskRepository.save(t);
            return "Updated";
        } else {
            return "Task not found";
        }
    }
}
